routeEnhancers:
  T3sportsMatch:
    type: Plugin
    routePath: '/spiel/{matchId}'
    namespace: 'cfc_league_fe'
    aspects:
      matchId:
        type: PersistedAliasMapper
        tableName: 'tx_cfcleague_games'
        routeFieldName: 'slug'
        lookupField: 'uid'

  T3sportsProfile:
    type: Plugin
    routePath: '/person/{profileId}'
    namespace: 'cfc_league_fe'
    aspects:
      profileId:
        type: PersistedAliasMapper
        tableName: 'tx_cfcleague_profiles'
        routeFieldName: 'slug'
        lookupField: 'uid'
